<?php

function wiil_jojo_menu() {
	$items = array();

	$items['brand/jojo'] = array(
		'title' => 'JOJO',
		'page callback' => ' ',
		'access arguments' => array('access content'),
	);
	$items['brand/jojo/about'] = array(
		'title' => 'JOJO|About',
		'page callback' => ' ',
		'access arguments' => array('access content'),
	);
	$items['brand/jojo/products'] = array(
		'title' => 'JOJO|Products',
		'page callback' => ' ',
		'access arguments' => array('access content'),
	);
	$items['brand/jojo/promotions'] = array(
		'title' => 'JOJO|Promotions',
		'page callback' => ' ',
		'access arguments' => array('access content'),
	);
	$items['brand/jojo/location'] = array(
		'title' => 'JOJO|Location',
		'page callback' => ' ',
		'access arguments' => array('access content'),
	);

	return $items;
}