<?php

/*
* @file
** Code for the WIIL Jojo Brand page
*/

/*
** Implements hook_menu()
*/
function wiil_brands_jojo_menu()
{	$items['brands/jojo'] = array(
		'title' => 'Jojo',
		'page callback' => 'wiil_brands_jojo_page',
		'access arguments' => array('access content'),
	);
	return $items;
}

/*
** Callback function for Jojo brands page.
*/
function wiil_brands_jojo_page(){
	return theme('jojo');
}

/*
** Implements hook_theme()
*/
function wiil_brands_jojo_theme(){
	$items = array();

	$items['jojo'] = array(
		'template' => 'templates/wiil-brands-jojo'
	);
	return $items;
}