<?php

/*
 * Implements hook_menu().
 */
function wiil_home_menu() {
	$items['home'] = array(
		'title' => 'Home',
		'page callback' => 'wiil_home_page',
		'access arguments' => array('access content'),
	);
	$items['about'] = array(
		'title' => 'About',
		'page callback' => 'wiil_about_page',
		'access arguments' => array('access content'),
	);
	$items['brand'] = array(
		'title' => 'Brand',
		'page callback' => 'wiil_brand_page',
		'access arguments' => array('access content'),
	);
	$items['contact'] = array(
		'title' => 'Contact',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('wiil_contact_form'),
		'access callback' => TRUE,
	);
	$items['news'] = array(
		'title' => 'News & Promotions',
		'page callback' => 'wiil_news_page',
		'access arguments' => array('access content'),
	);
	$items['members'] = array(
		'title' => 'Members Login',
		'page callback' => 'wiil_members_page',
		'access arguments' => array('access content'),
	);

	return $items;
}

function wiil_contact_form($form, &$form_state) {
	$form['first_name'] = array(
		'#type' => 'tetxfield',
		'#title' => t('First Name'),
		'#default_value' => 'Bob',
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
	);
	$form['last_name'] = array(
		'#type' => 'textfield',
		'#title' => t('Last Name'),
		'#default_value' => 'Lee',
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#default_value' => 'user@gmail.com',
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
	);
	$form['message'] = array(
		'#title' => 'Message',
		'#type' => 'textarea',
		'#description' => 'Please write your message here.',
		'#default_value' => '',
	);
	$form['submit_button'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);

	return $form;
}

/**
 * Form submit handler.
 */
function wiil_contact_form_submit($form, &$form_state) {
	drupal_goto('');
}

/**
 * Callback function for home page.
 */
function wiil_home_page() {
	return theme('home');
}

/**
 * Implements hook_theme().
 */
function wiil_home_theme() {
	$items = array();

	$items['home'] = array(
		'template' => 'templates/wiil-home',
	);

	return $items;
}

/**
 * Implements hook_block_info().
 */
function wiil_home_block_info() {
	$blocks = array();

	$blocks['brand_1'] = array(
		'info' => 'Home - Swiss O Par',
	);
	$blocks['brand_2'] = array(
		'info' => 'Home - inspira',
	);
	$blocks['brand_3'] = array(
		'info' => 'Home - jojo',
	);

	return $blocks;
}

/**
 *	Implements hook_block_view().
 */
function wiil_home_block_view($delta = '') {
	$block = array();

	switch ($delta) {
		case 'brand_1' :
			$block['content'] = ' ';
			break;
		case 'brand_2' :
			$block['content'] = ' ';
			break;
		case 'brand_3' :
			$block['content'] = ' ';
			break;
	}

	return $block;

}