<?php
/**
 * @file
 * Code for the WIIL Home Page feature.
 */

include_once 'wiil_home.features.inc';

function wiil_home_init() {
	drupal_add_js(drupal_get_path('module', 'wiil_home') . '/js/wiil_home.js');
}

/*
 * Implements hook_menu().
 */
function wiil_home_menu() {
	$items['home'] = array(
		'title' => 'Home',
		'page callback' => 'wiil_home_page',
		'access arguments' => array('access content'),
	);
	$items['about'] = array(
		'title' => 'About',
		'page callback' => 'wiil_about_page',
		'access arguments' => array('access content'),
	);
	$items['brand'] = array(
		'title' => 'Brand',
		'page callback' => 'wiil_brand_page',
		'access arguments' => array('access content'),
	);
	$items['contact'] = array(
		'title' => 'Contact',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('wiil_contact_form'),
		'access callback' => TRUE,
	);
	$items['news'] = array(
		'title' => 'News & Promotions',
		'page callback' => 'wiil_news_page',
		'access arguments' => array('access content'),
	);
	$items['members'] = array(
		'title' => 'Members Login',
		'page callback' => 'wiil_members_page',
		'access arguments' => array('access content'),
	);

	return $items;
}

function wiil_contact_form($form, &$form_state) {
	$form['first_name'] = array(
		'#type' => 'textfield',
		'#title' => t('First Name'),
		'#default_value' => 'Bob',
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
	);
	$form['last_name'] = array(
		'#type' => 'textfield',
		'#title' => t('Last Name'),
		'#default_value' => 'Lee',
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#default_value' => 'user@gmail.com',
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
	);
	$form['message'] = array(
		'#title' => 'Message',
		'#type' => 'textarea',
		'#description' => 'Please write your message here.',
		'#default_value' => '',
	);
	$form['submit_button'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);

	return $form;
}

/**
 * Form submit handler.
 */
function wiil_contact_form_submit($form, &$form_state) {
	$query = db_insert('contact_information')
		->fields(array(
			'first_name' => $form['first_name']['#value'],
			'last_name' => $form['last_name']['#value'],
			'email' => $form['email']['#value'],
			'message' => $form['message']['#value'],
		))
		->execute();

	drupal_goto('contact');
}

/**
 * Callback function for home page.
 */
function wiil_home_page() {
	return theme('home');
}

/**
* Callback function for about page.
*/
function wiil_about_page(){
	return theme('about');
}

/**
 * Implements hook_theme().
 */
function wiil_home_theme() {
	$items = array();

	$items['home'] = array(
		'template' => 'templates/wiil-home',
	);
	$items['header'] = array(
		'template' => 'templates/wiil-header',
	);
	$items['footer'] = array(
		'template' => 'templates/wiil-footer',
	);
	$items['about'] = array(
		'template' => 'templates/wiil-about',
	);

	return $items;
}

/**
 * Implements hook_block_info().
 */
function wiil_home_block_info() {
	$blocks = array();


	$blocks['header'] = array(
		'info' => 'Global - Header',
	);
	$blocks['footer'] = array(
		'info' => 'Global - Footer',
	);
	$blocks['brand_1'] = array(
		'info' => 'Home - Swiss O Par',
	);
	$blocks['brand_2'] = array(
		'info' => 'Home - inspira',
	);
	$blocks['brand_3'] = array(
		'info' => 'Home - jojo',
	);

	return $blocks;
}

/**
 *	Implements hook_block_view().
 */
function wiil_home_block_view($delta = '') {
	$block = array();

	switch ($delta) {
		case 'brand_1' :
			$block['content'] = ' ';
			break;
		case 'brand_2' :
			$block['content'] = ' ';
			break;
		case 'brand_3' :
			$block['content'] = ' ';
			break;
		case 'header' :
			$block['content'] = theme('header');
			break;
		case 'footer' :
			$block['content'] = theme('footer');
			break;
	}

	return $block;

}